package(default_visibility = ["//anodyne:default_visibility"])

cc_library(
    name = "npm_utils",
    srcs = ["npm_package.cc"],
    hdrs = ["npm_package.h"],
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_tencent_rapidjson//:rapidjson",
        "@com_google_absl//absl/strings",
    ],
)
