package(default_visibility = ["//anodyne:default_visibility"])

cc_library(
    name = "extract",
    srcs = [
    ],
    hdrs = [
        "extractor.h",
    ],
    deps = [
        "@com_github_google_glog//:glog",
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/strings",
        "@io_kythe//kythe/cxx/common:kzip_writer",
        "@io_kythe//kythe/cxx/common/indexing:output",
    ],
)
